name: ESlint Test
on: [push, pull_request]

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint --fix

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style(eslint): Fixed eslint style format"